import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys =>
      {
        'en_US': {
          "Login required":"Login required",
          "Please log in to access all features, track your orders, and easily manage your personal account.":"Please log in to access all features, track your orders, and easily manage your personal account.",
          "Log in now":"Log in now",
          "The account has been suspended.":"The account has been suspended.",
          "Your account has been temporarily suspended or blacklisted for violating the site's terms and conditions of use.":"Your account has been temporarily suspended or blacklisted for violating the site's terms and conditions of use.",
          "Reason for the ban:":"Reason for the ban:",
          "Please contact support via email: support@designland.com":"Please contact support via email: support@designland.com",
          "Contacting Technical Support":"Contacting Technical Support",
          "Log out":"Log out",
          "Good":"Good",
          "Welcome,":"Welcome,",
          "This interface is for store customers only. Since your account is registered as (" : "This interface is for store customers only. Since your account is registered as (",
          "), please proceed to the product and order management dashboard.":"), please proceed to the product and order management dashboard.",
          "Redirecting to the dashboard...":"Redirecting to the dashboard...",
          "Go to the control panel":"Go to the control panel",
          "Unable to open the link.":"Unable to open the link.",
          "An error occurred while attempting to connect.":"An error occurred while attempting to connect.",
          "About Us":"About Us",
          "Contact us":"Contact us",
          "Frequently Asked Questions":"Frequently Asked Questions",
          "Terms and Policies":"Terms and Policies",
          "terms of use":"terms of use",
          "privacy policy":"privacy policy",
          "Version 1.0.0":"Version 1.0.0",
          "Welcome to our platform.":"Welcome to our platform.",
          "Specially designed to provide the best experience for custom designs and gifts.":"Specially designed to provide the best experience for custom designs and gifts.",
          "There are currently no frequently asked questions.":"There are currently no frequently asked questions.",
          "e-mail":"e-mail",
          "Contact number":"Contact number",
          "WhatsApp":"WhatsApp",
          "We are pleased to provide the best services and custom designs of the highest quality.":"We are pleased to provide the best services and custom designs of the highest quality.",
          "The product has been removed from the cart.":"The product has been removed from the cart.",
          "Your order has been successfully confirmed and is now being processed!":"Your order has been successfully confirmed and is now being processed!",
          "An error occurred while confirming the order:":"An error occurred while confirming the order:",
          "Shopping Cart":"Shopping Cart",
          "Please log in to view the shopping cart.":"Please log in to view the shopping cart.",
          "The cart is currently empty.":"The cart is currently empty.",
          "Total:":"Total:",
          "Order Confirmation (In Progress)":"Order Confirmation (In Progress)",
          "Password reset link sent to your email!":"Password reset link sent to your email!",
          "An error occurred while sending reset link":"An error occurred while sending reset link",
          "An unexpected error occurred":"An unexpected error occurred",
          "Forgot Password?":"Forgot Password?",
          "No worries, enter your registered email and we'll send you a link to reset your password.":"No worries, enter your registered email and we'll send you a link to reset your password.",
          "Email Address":"Email Address",
          "Please enter your email":"Please enter your email",
          "Enter a valid email address":"Enter a valid email address",
          "Send Reset Link":"Send Reset Link",
          "Back to Login":"Back to Login",
          "Check Your Email":"Check Your Email",
          "We sent a password reset link to:":"We sent a password reset link to:",
          "Return to Login":"Return to Login",
          "Didn't receive the email? Try again":"Didn't receive the email? Try again",
          "Filter Products":"Filter Products",
          "Reset All":"Reset All",
          "Category":"Category",
          "All Categories":"All Categories",
          "Subcategory":"Subcategory",
          "All Subcategories":"All Subcategories",
          "Price Range":"Price Range",
          "Apply Filters":"Apply Filters",
          "Search custom gifts, items...":"Search custom gifts, items...",
          "No categories found.":"No categories found.",
          "See All":"See All",
          "Special Offer":"Special Offer",
          "discount":"discount",
          "EGP":"EGP",
          "The offer has ended.":"The offer has ended.",
          "day":"day",
          "hour":"hour",
          "minute":"minute",
          "second":"second",
          "Login failed":"Login failed",
          "We were unable to verify the account details; please try again.":"We were unable to verify the account details; please try again.",
          "An error occurred while logging in.":"An error occurred while logging in.",
          "This email address is not registered with us.":"This email address is not registered with us.",
          "The password is incorrect; please check it and try again.":"The password is incorrect; please check it and try again.",
          "The email format is invalid.":"The email format is invalid.",
          "This account has been disabled. Please contact support.":"This account has been disabled. Please contact support.",
          "The email or password is incorrect.":"The email or password is incorrect.",
          "Attempts have been temporarily blocked due to too many incorrect attempts. Please try again later.":"Attempts have been temporarily blocked due to too many incorrect attempts. Please try again later.",
          "Unexpected error":"Unexpected error",
          "Make sure you are connected to the Internet and try again.":"Make sure you are connected to the Internet and try again.",
          "Failed to log out":"Failed to log out",
          "Sign In":"Sign In",
          "Sign in to access your orders and saved designs":"Sign in to access your orders and saved designs",
          "Password":"Password",
          "Password must be at least 6 characters":"Password must be at least 6 characters",
          "Welcome Back!":"Welcome Back!",
          "Explore customized gifts, order personalized items, and track your active orders effortlessly.":"Explore customized gifts, order personalized items, and track your active orders effortlessly.",
          "Home":"Home",
          "Profile":"Profile",
          "About":"About",
          "Error":"Error",
          "Notifications":"Notifications",
          "Please log in to view notifications.":"Please log in to view notifications.",
          "There are currently no notifications.":"There are currently no notifications.",
          "New notification":"New notification",
          "now":"now",
          "since":"since",
          "Category Products":"Category Products",
          "Search in this category...":"Search in this category...",
          "All":"All",
          "No products found in this category.":"No products found in this category.",
          'Product Title':'Product Title',
          "An error occurred during processing:":"An error occurred during processing:",
          "Please log in first to add products to the cart.":"Please log in first to add products to the cart.",
          "cancellation":"cancellation",
          "Log in":"Log in",
          "Complete contact and address details":"Complete contact and address details",
          "Contact phone number":"Contact phone number",
          "Address name (e.g., Home, Work)":"Address name (e.g., Home, Work)",
          "Full address details":"Full address details",
          "Please fill in all the details.":"Please fill in all the details.",
          "Data saved successfully! Order now.":"Data saved successfully! Order now.",
          "Save and track the order":"Save and track the order",
          "Order and Design Details":"Order and Design Details",
          "Select a delivery address:":"Select a delivery address:",
          "Google Drive image link":"Google Drive image link",
          "Additional notes on the request":"Additional notes on the request",
          "Write down any specific details or modifications you would like to be implemented...":"Write down any specific details or modifications you would like to be implemented...",
          "The product has been successfully added to your cart! 🎉":"The product has been successfully added to your cart! 🎉",
          "Confirm addition to cart":"Confirm addition to cart",
          "Product Details":"Product Details",
          "The product does not exist.":"The product does not exist.",
          "Add to cart":"Add to cart",
          "Detailed product information":"Detailed product information",
          "There is no additional description for the product.":"There is no additional description for the product.",
          "Customer Ratings and Reviews":"Customer Ratings and Reviews",
          "There are currently no ratings. Be the first to rate this product!":"There are currently no ratings. Be the first to rate this product!",
          "client":"client",
          "Add your rating":"Add your rating",
          "Write your opinion about the product here...":"Write your opinion about the product here...",
          "Publish the review":"Publish the review",
          "My Orders":"My Orders",
          "Pending":"Pending",
          "Delivery in progress":"Delivery in progress",
          "The Completed":"The Completed",
          "Cancelled":"Cancelled",
          "pending":"pending",
          "shipping":"shipping",
          "completed":"completed",
          "cancelled":"cancelled",
          "Cancel Order":"Cancel Order",
          "Are you sure you want to cancel this request?":"Are you sure you want to cancel this request?",
          "to retreat":"to retreat",
          "Confirm Cancellation":"Confirm Cancellation",
          "The order has been successfully cancelled.":"The order has been successfully cancelled.",
          "An error occurred while cancelling the order.":"An error occurred while cancelling the order.",
          "Please log in to view orders.":"Please log in to view orders.",
          "Order no":"Order no",
          "There are no requests available at the moment.":"There are no requests available at the moment.",
          "Edit personal information":"Edit personal information",
          "full name":"full name",
          "phone number":"phone number",
          "Save changes":"Save changes",
          "The data has been successfully updated.":"The data has been successfully updated.",
          "Address Management":"Address Management",
          "Add a new address:":"Add a new address:",
          "Address Name (e.g., Home)":"Address Name (e.g., Home)",
          "Add Address":"Add Address",
          "A password reset link will be sent to the email address:":"A password reset link will be sent to the email address:",
          "A reset link has been sent to your email.":"A reset link has been sent to your email.",
          "Send the link":"Send the link",
          "Order List and Tracking":"Order List and Tracking",
          "Update password":"Update password",
          "Change Language":"Change Language",
          "Do you want to clear all recorded searches?":"Do you want to clear all recorded searches?",
          "Clear search history":"Clear search history",
          "Delete":"Delete",
          "Search history":"Search history",
          "Please log in to view the history.":"Please log in to view the history.",
          "Search history is empty.":"Search history is empty.",
          "You haven't performed any searches recently.":"You haven't performed any searches recently.",
          "Failed to create the account.":"Failed to create the account.",
          "The passwords do not match.":"The passwords do not match.",
          "Sign Up":"Sign Up",
          "Please fill in your information to register":"Please fill in your information to register",
          "Full Name":"Full Name",
          "Please enter your full name":"Please enter your full name",
          "Confirm Password":"Confirm Password",
          "Passwords do not match":"Passwords do not match",
          "Create Account":"Create Account",
          "Already have an account?":"Already have an account?",
        },
        'ar_DZ': {
          "Login required":"تسجيل الدخول مطلوب",
          "Please log in to access all features, track your orders, and easily manage your personal account.":"يرجى تسجيل الدخول للوصول إلى كافة الميزات، ومتابعة طلباتك، وإدارة حسابك الشخصي بجميع سهولة.",
          "Log in now":"سجل الدخول الآن",
          "The account has been suspended.":"تم تعليق الحساب.",
          "Your account has been temporarily suspended or blacklisted for violating the site's terms and conditions of use.":"تم تعليق حسابك مؤقتًا أو وضعه في القائمة السوداء لمخالفة شروط وأحكام الاستخدام الخاصة بالموقع.",
          "Reason for the ban:":"سبب الحظر:",
          "Please contact support via email: support@designland.com":"يرجى التواصل مع الدعم عبر البريد الإلكتروني: support@designland.com",
          "Contacting Technical Support":"التواصل مع الدعم الفني",
          "Log out":"تسجيل الخروج",
          "Good":"جيد",
          "Welcome,":"أهلاً بك،",
          "This interface is for store customers only. Since your account is registered as (" : "هذه الواجهة مخصصة لعملاء المتجر فقط. وبما أن حسابك مسجل كـ (",
          "), please proceed to the product and order management dashboard.":")، يرجى الانتقال إلى لوحة تحكم إدارة المنتجات والطلبات.",
          "Redirecting to the dashboard...":"جاري إعادة التوجيه إلى لوحة التحكم...",
          "Go to the control panel":"الذهاب إلى لوحة التحكم",
          "Unable to open the link.":"تعذر فتح الرابط.",
          "An error occurred while attempting to connect.":"حدث خطأ أثناء محاولة الاتصال.",
          "About Us":"من نحن",
          "Contact us":"اتصل بنا",
          "Frequently Asked Questions":"الأسئلة الشائعة",
          "Terms and Policies":"الشروط والسياسات",
          "terms of use":"شروط الاستخدام",
          "privacy policy":"سياسة الخصوصية",
          "Version 1.0.0":"الإصدار 1.0.0",
          "Welcome to our platform.":"مرحبًا بك في منصتنا.",
          "Specially designed to provide the best experience for custom designs and gifts.":"صُممت خصيصًا لتقديم أفضل تجربة للتصاميم والهدايا المخصصة.",
          "There are currently no frequently asked questions.":"لا توجد أسئلة شائعة حاليًا.",
          "e-mail":"البريد الإلكتروني",
          "Contact number":"رقم التواصل",
          "WhatsApp":"واتساب",
          "We are pleased to provide the best services and custom designs of the highest quality.":"يسعدنا تقديم أفضل الخدمات والتصاميم المخصصة بأعلى جودة.",
          "The product has been removed from the cart.":"تمت إزالة المنتج من سلة التسوق.",
          "Your order has been successfully confirmed and is now being processed!":"تم تأكيد طلبك بنجاح وجاري معالجته الآن!",
          "An error occurred while confirming the order:":"حدث خطأ أثناء تأكيد الطلب:",
          "Shopping Cart":"سلة التسوق",
          "Please log in to view the shopping cart.":"يرجى تسجيل الدخول لعرض سلة التسوق.",
          "The cart is currently empty.":"سلة التسوق فارغة حاليًا.",
          "Total:":"الإجمالي:",
          "Order Confirmation (In Progress)":"تأكيد الطلب (قيد التنفيذ)",
          "Password reset link sent to your email!":"تم إرسال رابط إعادة تعيين كلمة المرور إلى بريدك الإلكتروني!",
          "An error occurred while sending reset link":"حدث خطأ أثناء إرسال رابط إعادة التعيين",
          "An unexpected error occurred":"حدث خطأ غير متوقع",
          "Forgot Password?":"هل نسيت كلمة المرور؟",
          "No worries, enter your registered email and we'll send you a link to reset your password.":"لا تقلق، أدخل بريدك الإلكتروني المسجل وسنرسل لك رابطًا لإعادة تعيين كلمة المرور.",
          "Email Address":"عنوان البريد الإلكتروني",
          "Please enter your email":"يرجى إدخال البريد الإلكتروني",
          "Enter a valid email address":"أدخل عنوان بريد إلكتروني صحيح",
          "Send Reset Link":"إرسال رابط إعادة التعيين",
          "Back to Login":"العودة لتسجيل الدخول",
          "Check Your Email":"تفقد بريدك الإلكتروني",
          "We sent a password reset link to:":"قمنا بإرسال رابط إعادة تعيين كلمة المرور إلى:",
          "Return to Login":"العودة إلى تسجيل الدخول",
          "Didn't receive the email? Try again":"لم يصلك البريد الإلكتروني؟ حاول مرة أخرى",
          "Filter Products":"تصفية المنتجات",
          "Reset All":"إعادة ضبط الكل",
          "Category":"الفئة",
          "All Categories":"جميع الفئات",
          "Subcategory":"الفئة الفرعية",
          "All Subcategories":"جميع الفئات الفرعية",
          "Price Range":"نطاق السعر",
          "Apply Filters":"تطبيق الفلاتر",
          "Search custom gifts, items...":"ابحث عن هدايا مخصصة، منتجات...",
          "No categories found.":"لم يتم العثور على فئات.",
          "See All":"عرض الكل",
          "Special Offer":"عرض خاص",
          "discount":"خصم",
          "EGP":"ج.م",
          "The offer has ended.":"انتهى العرض.",
          "day":"يوم",
          "hour":"ساعة",
          "minute":"دقيقة",
          "second":"ثانية",
          "Login failed":"فشل تسجيل الدخول",
          "We were unable to verify the account details; please try again.":"تعذر التحقق من تفاصيل الحساب؛ يرجى المحاولة مرة أخرى.",
          "An error occurred while logging in.":"حدث خطأ أثناء تسجيل الدخول.",
          "This email address is not registered with us.":"عنوان البريد الإلكتروني هذا غير مسجل لدينا.",
          "The password is incorrect; please check it and try again.":"كلمة المرور غير صحيحة؛ يرجى التحقق منها والمحاولة مرة أخرى.",
          "The email format is invalid.":"صيغة البريد الإلكتروني غير صالحة.",
          "This account has been disabled. Please contact support.":"تم تعطيل هذا الحساب. يرجى الاتصال بالدعم.",
          "The email or password is incorrect.":"البريد الإلكتروني أو كلمة المرور غير صحيحة.",
          "Attempts have been temporarily blocked due to too many incorrect attempts. Please try again later.":"تم حظر المحاولات مؤقتًا بسبب كثرة المحاولات الخاطئة. يرجى المحاولة لاحقًا.",
          "Unexpected error":"خطأ غير متوقع",
          "Make sure you are connected to the Internet and try again.":"تأكد من اتصالك بالإنترنت ثم حاول مرة أخرى.",
          "Failed to log out":"فشل تسجيل الخروج",
          "Sign In":"تسجيل الدخول",
          "Sign in to access your orders and saved designs":"سجل الدخول للوصول إلى طلباتك والتصاميم المحفوظة",
          "Password":"كلمة المرور",
          "Password must be at least 6 characters":"يجب أن تتكون كلمة المرور من 6 أحرف على الأقل",
          "Welcome Back!":"مرحبًا بعودتك!",
          "Explore customized gifts, order personalized items, and track your active orders effortlessly.":"استكشف الهدايا المخصصة، واطلب منتجات فريدة، وتتبع طلباتك الحالية بكل سهولة.",
          "Home":"الرئيسية",
          "Profile":"الملف الشخصي",
          "About":"حول",
          "Error":"خطأ",
          "Notifications":"الإشعارات",
          "Please log in to view notifications.":"يرجى تسجيل الدخول لعرض الإشعارات.",
          "There are currently no notifications.":"لا توجد إشعارات حاليًا.",
          "New notification":"إشعار جديد",
          "now":"الآن",
          "since":"منذ",
          "Category Products":"منتجات الفئة",
          "Search in this category...":"البحث في هذه الفئة...",
          "All":"الكل",
          "No products found in this category.":"لم يتم العثور على منتجات في هذه الفئة.",
          'Product Title':'عنوان المنتج',
          "An error occurred during processing:":"حدث خطأ أثناء المعالجة:",
          "Please log in first to add products to the cart.":"يرجى تسجيل الدخول أولاً لإضافة المنتجات إلى السلة.",
          "cancellation":"إلغاء",
          "Log in":"تسجيل الدخول",
          "Complete contact and address details":"استكمال بيانات التواصل والعنوان",
          "Contact phone number":"رقم هاتف التواصل",
          "Address name (e.g., Home, Work)":"اسم العنوان (مثل: المنزل، العمل)",
          "Full address details":"تفاصيل العنوان بالكامل",
          "Please fill in all the details.":"يرجى ملء كافة التفاصيل.",
          "Data saved successfully! Order now.":"تم حفظ البيانات بنجاح! اطلب الآن.",
          "Save and track the order":"حفظ ومتابعة الطلب",
          "Order and Design Details":"تفاصيل الطلب والتصميم",
          "Select a delivery address:":"اختر عنوان التوصيل:",
          "Google Drive image link":"رابط الصورة على جوجل درايف",
          "Additional notes on the request":"ملاحظات إضافية على الطلب",
          "Write down any specific details or modifications you would like to be implemented...":"اكتب أي تفاصيل أو تعديلات خاصة ترغب في تنفيذها...",
          "The product has been successfully added to your cart! 🎉":"تمت إضافة المنتج بنجاح إلى سلة التسوق! 🎉",
          "Confirm addition to cart":"تأكيد الإضافة إلى السلة",
          "Product Details":"تفاصيل المنتج",
          "The product does not exist.":"المنتج غير موجود.",
          "Add to cart":"إضافة إلى السلة",
          "Detailed product information":"معلومات المنتج التفصيلية",
          "There is no additional description for the product.":"لا يوجد وصف إضافي للمنتج.",
          "Customer Ratings and Reviews":"تقييمات وآراء العملاء",
          "There are currently no ratings. Be the first to rate this product!":"لا توجد تقييمات حاليًا. كن أول من يقيم هذا المنتج!",
          "client":"عميل",
          "Add your rating":"أضف تقييمك",
          "Write your opinion about the product here...":"اكتب رأيك عن المنتج هنا...",
          "Publish the review":"نشر التقييم",
          "My Orders":"طلباتي",
          "Pending":"قيد الانتظار",
          "Delivery in progress":"جاري التوصيل",
          "The Completed":"المكتملة",
          "Cancelled":"الملغاة",
          "pending":"قيد الانتظار",
          "shipping":"جاري الشحن",
          "completed":"مكتمل",
          "cancelled":"ملغى",
          "Cancel Order":"إلغاء الطلب",
          "Are you sure you want to cancel this request?":"هل أنت تأكد من أنك تريد إلغاء هذا الطلب؟",
          "to retreat":"تراجع",
          "Confirm Cancellation":"تأكيد الإلغاء",
          "The order has been successfully cancelled.":"تم إلغاء الطلب بنجاح.",
          "An error occurred while cancelling the order.":"حدث خطأ أثناء إلغاء الطلب.",
          "Please log in to view orders.":"يرجى تسجيل الدخول لعرض الطلبات.",
          "Order no":"رقم الطلب",
          "There are no requests available at the moment.":"لا توجد طلبات متاحة في الوقت الحالي.",
          "Edit personal information":"تعديل المعلومات الشخصية",
          "full name":"الاسم الكامل",
          "phone number":"رقم الهاتف",
          "Save changes":"حفظ التغييرات",
          "The data has been successfully updated.":"تم تحديث البيانات بنجاح.",
          "Address Management":"إدارة العناوين",
          "Add a new address:":"إضافة عنوان جديد:",
          "Address Name (e.g., Home)":"اسم العنوان (مثل: المنزل)",
          "Add Address":"إضافة عنوان",
          "A password reset link will be sent to the email address:":"سيتم إرسال رابط إعادة تعيين كلمة المرور إلى البريد الإلكتروني:",
          "A reset link has been sent to your email.":"تم إرسال رابط إعادة التعيين إلى بريدك الإلكتروني.",
          "Send the link":"إرسال الرابط",
          "Order List and Tracking":"قائمة الطلبات ومتابعتها",
          "Update password":"تحديث كلمة المرور",
          "Change Language":"تغيير اللغة",
          "Do you want to clear all recorded searches?":"هل تريد مسح جميع عمليات البحث المسجلة؟",
          "Clear search history":"مسح سجل البحث",
          "Delete":"حذف",
          "Search history":"سجل البحث",
          "Please log in to view the history.":"يرجى تسجيل الدخول لعرض السجل.",
          "Search history is empty.":"سجل البحث فارغ.",
          "You haven't performed any searches recently.":"لم تقم بأي عمليات بحث مؤخرًا.",
          "Failed to create the account.":"فشل إنشاء الحساب.",
          "The passwords do not match.":"كلمتا المرور غير متطابقتين.",
          "Sign Up":"إنشاء حساب",
          "Please fill in your information to register":"يرجى ملء بياناتك للتسجيل",
          "Full Name":"الاسم الكامل",
          "Please enter your full name":"يرجى إدخال اسمك الكامل",
          "Confirm Password":"تأكيد كلمة المرور",
          "Passwords do not match":"كلمتا المرور غير متطابقتين",
          "Create Account":"إنشاء حساب",
          "Already have an account?":"لديك حساب بالفعل؟"
                 },
      };
}